CREATE TABLE CMS_ITEM
(
    ITEM_ID       NUMBER NOT NULL PRIMARY KEY,
    TITLE         VARCHAR2(50),
    CONTENT       CLOB,
    CATEGORY_ID   NUMBER,
    TYPE_ID       NUMBER,
    MASTER_ID     NUMBER,
    VERSION       NUMBER,
    OWNER         VARCHAR2(50),
    CREATED_DATE  DATE,
    UPDATER       VARCHAR2(50),
    UPDATED_DATE  DATE,
    STATUS        varchar2(10),
    LANGUAGE      VARCHAR2(2)
)
;
ALTER TABLE CMS_ITEM ADD PUBLISH_DATE DATE DEFAULT(SYSDATE) NOT NULL;
CREATE SEQUENCE cms_item_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE cms_item_master_seq START WITH 1 INCREMENT BY 1;

