CREATE TABLE CMS_ITEM_PROPERTY
(
    PROPERTY_ID     NUMBER,
    PROPERTY_LABEL  VARCHAR2(50),
    PROPERTY_NAME   VARCHAR2(50),
    PROPERTY_TYPE   VARCHAR2(20),
    LANGUAGE        VARCHAR2(2),
    RESOURCE_ID     NUMBER
)
;
ALTER TABLE CMS_ITEM_PROPERTY ADD UPDATED_DATE DATE;

CREATE SEQUENCE CMS_ITEM_PROPERTY_SEQ START WITH 1 INCREMENT BY 1;
/
