CREATE TABLE CMS_FOLDER
(
    FOLDER_ID    NUMBER(8,2),
    FOLDER_NAME  VARCHAR2(50),
    OWNER        VARCHAR(50),
    IS_PUBLIC       NUMBER(8,2)
)
;
ALTER TABLE CMS_FOLDER ADD PARENT_ID NUMBER;
CREATE SEQUENCE CMS_FOLDER_SEQ start with 1 increment by 1;


