CREATE TABLE CMS_ITEM_FILES
(
    ID            NUMBER PRIMARY KEY NOT NULL,
    ITEM_ID       NUMBER,
    FILE_ID       NUMBER,
    ORDER_NUMBER  NUMBER
)
;
CREATE SEQUENCE CMS_ITEM_FILES_SEQ START WITH 1 INCREMENT BY 1;


