--drop TABLE CMS_TYPE_PROPERTIES;
CREATE TABLE CMS_TYPE_PROPERTIES
(
    ID            NUMBER,
    TYPE_ID       NUMBER,
    PROPERTY_ID   NUMBER,
    PROPERTY_LABEL VARCHAR2(50),
    ORDER_NUMBER  NUMBER,
    IS_REQUIRED   NUMBER
)
;

CREATE SEQUENCE CMS_TYPE_PROPERTIES_SEQ START WITH 1 INCREMENT BY 1;


