--drop table CMS_ITEM_TYPES;
CREATE TABLE CMS_ITEM_TYPE
(
    TYPE_ID           NUMBER(8,2) NOT NULL,
    TITLE_LABEL       VARCHAR(50),
    TYPE_NAME         VARCHAR2(50),
    TYPE_DESCRIPTION  VARCHAR2(50),
    USE_CATEGORY      NUMBER(1),
    USE_PERSPECTIVE   NUMBER(1),
    CONTENT_LABEL     VARCHAR2(50),
    STATUS            varchar2(50),
    LANGUAGE          VARCHAR2(50)
)
;
ALTER TABLE CMS_ITEM_TYPE ADD UPDATED_DATE DATE;

ALTER TABLE CMS_ITEM_TYPE ADD CONSTRAINT PK_CMS_ITEM_TYPES 
    PRIMARY KEY (TYPE_ID)
;
CREATE SEQUENCE CMS_ITEM_TYPE_SEQ START WITH 1 INCREMENT BY 1;

