CREATE TABLE JPDK_PREFERENCE_STORE2 (
  PATH_TYPE       VARCHAR2 (60)  NOT NULL,
  REFERENCE_PATH  VARCHAR2 (250)  NOT NULL,
  SEARCH_PATH     VARCHAR2 (250)  NOT NULL,
  DATA_CLASS      VARCHAR2 (250),
  LONG_VALUE      LONG RAW,
  CONSTRAINT JPS2_PK
  PRIMARY KEY ( REFERENCE_PATH, PATH_TYPE ) ) ;

  CREATE INDEX JPDK_PATH_TYPES2 ON
  JPDK_PREFERENCE_STORE2(PATH_TYPE);

  CREATE INDEX JPDK_SEARCH_PREFS2 ON
  JPDK_PREFERENCE_STORE2(SEARCH_PATH);
