CREATE TABLE STRUTS_TOKEN(ID NUMBER PRIMARY KEY NOT NULL,TOKEN NUMBER NOT NULL);
CREATE SEQUENCE STRUTS_TOKEN_ID_SEQ START WITH 1 INCREMENT BY 1;
--CREATE SEQUENCE STRUTS_TOKEN_TOKEN_SEQ START WITH 1 INCREMENT BY 1;
